import { Pool, type QueryResultRow } from "pg";
import {
  type AlbumRow,
  type ArchiveContextResult,
  type ArchiveQuery,
  type ArchiveSearchResult,
  type ArchiveStore,
  type BatchResult,
  type ChatRecord,
  type LastMessageInfo,
  type MediaRow,
  type MessageRecord,
  type MessageRow,
  type StoredMediaFile,
  groupKey,
  mediaKey,
  normalizeContextLimit,
  normalizeLimit,
  normalizeOffset,
  normalizeRowId,
  normalizeTimeMode,
  paramPlaceholders,
  splitTerms,
  toIsoDate
} from "./model.js";

const SCHEMA_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;

export class PostgresArchiveStore implements ArchiveStore {
  private readonly pool: Pool;
  private readonly schema: string;

  constructor(readonly url: string, schema = "public") {
    if (!SCHEMA_PATTERN.test(schema)) throw new Error(`invalid schema name: ${schema}`);
    this.schema = quoteIdentifier(schema);
    this.pool = new Pool({ connectionString: url });
  }

  async init(): Promise<void> {
    const client = await this.pool.connect();
    try {
      await client.query(`CREATE SCHEMA IF NOT EXISTS ${this.schema}`);
      await client.query(`
        CREATE TABLE IF NOT EXISTS ${this.table("messages")} (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          message_id BIGINT NOT NULL,
          chat_id TEXT NOT NULL,
          grouped_id TEXT,
          chat_title TEXT,
          sender_id TEXT,
          sender_username TEXT,
          sender_first_name TEXT,
          sender_last_name TEXT,
          date TIMESTAMPTZ NOT NULL,
          text TEXT,
          message_type TEXT DEFAULT 'text',
          reply_to_msg_id BIGINT,
          forward_from_id TEXT,
          forward_from_name TEXT,
          has_media BOOLEAN DEFAULT FALSE,
          media_type TEXT,
          media_path TEXT,
          created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          UNIQUE(message_id, chat_id)
        );
        CREATE INDEX IF NOT EXISTS idx_messages_chat_date
          ON ${this.table("messages")} (chat_id, date);
        CREATE INDEX IF NOT EXISTS idx_messages_chat_date_id
          ON ${this.table("messages")} (chat_id, date, id);
        CREATE INDEX IF NOT EXISTS idx_messages_chat_grouped
          ON ${this.table("messages")} (chat_id, grouped_id);
        CREATE INDEX IF NOT EXISTS idx_messages_sender
          ON ${this.table("messages")} (sender_id);
        CREATE TABLE IF NOT EXISTS ${this.table("media_files")} (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          message_id BIGINT NOT NULL,
          chat_id TEXT NOT NULL,
          media_type TEXT NOT NULL,
          file_name TEXT NOT NULL,
          file_path TEXT NOT NULL,
          file_size BIGINT,
          mime_type TEXT,
          created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (message_id, chat_id)
            REFERENCES ${this.table("messages")} (message_id, chat_id)
            ON DELETE CASCADE
        );
        CREATE INDEX IF NOT EXISTS idx_media_message
          ON ${this.table("media_files")} (message_id, chat_id);
        CREATE TABLE IF NOT EXISTS ${this.table("chats")} (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          chat_id TEXT UNIQUE NOT NULL,
          title TEXT,
          username TEXT,
          type TEXT,
          description TEXT,
          members_count BIGINT,
          last_sync TIMESTAMPTZ,
          created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS ${this.table("sync_history")} (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          chat_id TEXT NOT NULL,
          start_date TIMESTAMPTZ,
          end_date TIMESTAMPTZ,
          messages_count BIGINT,
          media_count BIGINT,
          sync_started_at TIMESTAMPTZ,
          sync_completed_at TIMESTAMPTZ,
          status TEXT DEFAULT 'running'
        );
      `);
    } finally {
      client.release();
    }
  }

  async close(): Promise<void> {
    await this.pool.end();
  }

  async saveChat(chat: ChatRecord): Promise<boolean> {
    await this.pool.query(
      `INSERT INTO ${this.table("chats")}
        (chat_id, title, username, type, description, members_count, last_sync)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       ON CONFLICT (chat_id) DO UPDATE SET
         title = EXCLUDED.title,
         username = EXCLUDED.username,
         type = EXCLUDED.type,
         description = EXCLUDED.description,
         members_count = EXCLUDED.members_count,
         last_sync = EXCLUDED.last_sync`,
      [chat.chatId, chat.title ?? null, chat.username ?? null, chat.type ?? null,
       chat.description ?? null, chat.membersCount ?? null, new Date().toISOString()]
    );
    return true;
  }

  async startSyncSession(chatId: string, startDate: string, endDate: string): Promise<number> {
    const result = await this.pool.query(
      `INSERT INTO ${this.table("sync_history")}
        (chat_id, start_date, end_date, sync_started_at, status)
       VALUES ($1, $2::timestamptz, $3::timestamptz, $4, 'running')
       RETURNING id`,
      [chatId, startDate, endDate, new Date().toISOString()]
    );
    return Number(result.rows[0]?.id ?? -1);
  }

  async completeSyncSession(
    sessionId: number,
    messagesCount: number,
    mediaCount: number
  ): Promise<void> {
    if (sessionId < 0) return;
    await this.pool.query(
      `UPDATE ${this.table("sync_history")}
          SET sync_completed_at = $1, messages_count = $2, media_count = $3, status = 'completed'
        WHERE id = $4`,
      [new Date().toISOString(), messagesCount, mediaCount, sessionId]
    );
  }

  async getLastMessageInfo(chatId: string): Promise<LastMessageInfo | undefined> {
    const result = await this.pool.query(
      `SELECT message_id, date FROM ${this.table("messages")}
        WHERE chat_id = $1
        ORDER BY date DESC, message_id DESC
        LIMIT 1`,
      [chatId]
    );
    const row = result.rows[0];
    return row ? { messageId: Number(row.message_id), date: toIsoDate(row.date) } : undefined;
  }

  async messageIdsExist(chatId: string, messageIds: readonly number[]): Promise<ReadonlySet<number>> {
    const ids = [...new Set(messageIds.map(Number))];
    if (!ids.length) return new Set();
    const placeholders = ids.map((_, index) => `$${index + 2}`).join(", ");
    const result = await this.pool.query(
      `SELECT message_id FROM ${this.table("messages")}
        WHERE chat_id = $1 AND message_id IN (${placeholders})`,
      [chatId, ...ids]
    );
    return new Set(result.rows.map((row) => Number(row.message_id)));
  }

  async saveBatch(messages: readonly MessageRow[], media: readonly MediaRow[]): Promise<BatchResult> {
    if (!messages.length) return { messages: 0, media: 0 };
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN");
      const messagePlaceholders = messages
        .map((_, index) => `(${paramPlaceholders(index * 18 + 1, 18)})`)
        .join(", ");
      const messageValues: unknown[] = [];
      for (const row of messages) {
        messageValues.push(
          row.messageId,
          row.chatId,
          row.groupedId ?? null,
          row.chatTitle ?? null,
          row.senderId ?? null,
          row.senderUsername ?? null,
          row.senderFirstName ?? null,
          row.senderLastName ?? null,
          toIsoDate(row.date),
          row.text,
          row.messageType ?? "text",
          row.replyToMsgId ?? null,
          row.forwardFromId ?? null,
          row.forwardFromName ?? null,
          row.hasMedia,
          row.mediaType ?? null,
          row.mediaPath ?? null,
          new Date().toISOString()
        );
      }
      const inserted = await client.query(
        `INSERT INTO ${this.table("messages")}
          (message_id, chat_id, grouped_id, chat_title, sender_id, sender_username,
           sender_first_name, sender_last_name, date, text, message_type,
           reply_to_msg_id, forward_from_id, forward_from_name,
           has_media, media_type, media_path, created_at)
         VALUES ${messagePlaceholders}
         ON CONFLICT (message_id, chat_id) DO NOTHING`,
        messageValues
      );

      let mediaInserted = 0;
      if (media.length) {
        const mediaPlaceholders = media
          .map((_, index) => `(${paramPlaceholders(index * 7 + 1, 7)})`)
          .join(", ");
        const mediaValues: unknown[] = [];
        for (const row of media) {
          mediaValues.push(
            row.messageId,
            row.chatId,
            row.mediaType,
            row.fileName,
            row.filePath,
            row.fileSize ?? null,
            row.mimeType ?? null
          );
        }
        const mediaResult = await client.query(
          `INSERT INTO ${this.table("media_files")}
            (message_id, chat_id, media_type, file_name, file_path, file_size, mime_type)
           VALUES ${mediaPlaceholders}`,
          mediaValues
        );
        mediaInserted = mediaResult.rowCount ?? 0;
      }
      await client.query("COMMIT");
      return { messages: inserted.rowCount ?? 0, media: mediaInserted };
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }
  }

  async searchStructured(query: ArchiveQuery): Promise<ArchiveSearchResult> {
    const { where, values } = buildWhere(query);
    const limit = normalizeLimit(query.limit);
    const offset = normalizeOffset(query.offset);
    const count = await this.pool.query(
      `SELECT COUNT(*)::int AS count FROM ${this.table("messages")} m ${where}`,
      values
    );
    const rows = await this.pool.query(
      `${messageSelect(this.table("messages"), this.table("media_files"))}
       ${where}
       ORDER BY m.date DESC, m.id DESC
       LIMIT $${values.length + 1} OFFSET $${values.length + 2}`,
      [...values, limit, offset]
    );
    return {
      items: await this.attachMedia(rows.rows),
      total: Number(count.rows[0]?.count ?? 0),
      limit,
      offset
    };
  }

  async getMessageByRowId(rowId: string): Promise<MessageRecord | undefined> {
    const result = await this.pool.query(
      `${messageSelect(this.table("messages"), this.table("media_files"))}
       WHERE m.id = $1::bigint
       LIMIT 1`,
      [normalizeRowId(rowId)]
    );
    return result.rows.length ? (await this.attachMedia(result.rows))[0] : undefined;
  }

  async getMessageContext(
    rowId: string,
    beforeN: number,
    afterN: number
  ): Promise<ArchiveContextResult> {
    const beforeLimit = normalizeContextLimit(beforeN);
    const afterLimit = normalizeContextLimit(afterN);
    const anchor = await this.getMessageByRowId(rowId);
    if (!anchor) {
      return { anchor: undefined, before: [], after: [], beforeN: beforeLimit, afterN: afterLimit };
    }

    const beforeResult = beforeLimit
      ? await this.pool.query(
          `${messageSelect(this.table("messages"), this.table("media_files"))}
           WHERE m.chat_id = $1
             AND (m.date < $2::timestamptz OR (m.date = $2::timestamptz AND m.id < $3::bigint))
           ORDER BY m.date DESC, m.id DESC
           LIMIT $4`,
          [anchor.chatId, anchor.date, anchor.rowId, beforeLimit]
        )
      : { rows: [] as QueryResultRow[] };
    const afterResult = afterLimit
      ? await this.pool.query(
          `${messageSelect(this.table("messages"), this.table("media_files"))}
           WHERE m.chat_id = $1
             AND (m.date > $2::timestamptz OR (m.date = $2::timestamptz AND m.id > $3::bigint))
           ORDER BY m.date ASC, m.id ASC
           LIMIT $4`,
          [anchor.chatId, anchor.date, anchor.rowId, afterLimit]
        )
      : { rows: [] as QueryResultRow[] };
    return {
      anchor,
      before: await this.attachMedia([...beforeResult.rows].reverse()),
      after: await this.attachMedia(afterResult.rows),
      beforeN: beforeLimit,
      afterN: afterLimit
    };
  }

  async getMediaFileById(id: string): Promise<StoredMediaFile | undefined> {
    const result = await this.pool.query(
      `SELECT id::text AS id, message_id, chat_id, media_type, file_name, file_path,
              file_size, mime_type
         FROM ${this.table("media_files")}
        WHERE id = $1::bigint
        LIMIT 1`,
      [normalizeRowId(id)]
    );
    return result.rows.length ? toStoredMediaFile(result.rows[0]) : undefined;
  }

  private async attachMedia(rows: readonly QueryResultRow[]): Promise<MessageRecord[]> {
    if (!rows.length) return [];
    const pairKeys = rows.map((row) => [String(row.chat_id), Number(row.message_id)] as const);
    const groupKeys = rows
      .filter((row) => row.grouped_id !== null && row.grouped_id !== undefined)
      .map((row) => [String(row.chat_id), String(row.grouped_id)] as const);

    const mediaMap = await this.fetchMediaFiles(pairKeys);
    const albumMap = groupKeys.length
      ? await this.fetchAlbumRows(groupKeys)
      : new Map<string, AlbumRow[]>();

    return rows.map((row) => toMessageRecord(row, mediaMap, albumMap));
  }

  private async fetchMediaFiles(
    pairs: readonly (readonly [string, number])[]
  ): Promise<Map<string, StoredMediaFile[]>> {
    const { clause, params } = pairSql("message_id", pairs);
    const result = await this.pool.query(
      `SELECT id::text AS id, message_id, chat_id, media_type, mime_type
         FROM ${this.table("media_files")}
        WHERE ${clause}
        ORDER BY id ASC`,
      params
    );
    const map = new Map<string, StoredMediaFile[]>();
    for (const row of result.rows) {
      pushGrouped(map, mediaKey(String(row.chat_id), Number(row.message_id)), toStoredMediaFile(row));
    }
    return map;
  }

  private async fetchAlbumRows(pairs: readonly (readonly [string, string])[]): Promise<Map<string, AlbumRow[]>> {
    const { clause, params } = pairSql("grouped_id", pairs);
    const result = await this.pool.query(
      `${albumSelect(this.table("messages"), this.table("media_files"))}
       WHERE m.has_media = TRUE AND ${clause}
       ORDER BY m.date ASC, m.id ASC`,
      params
    );
    const map = new Map<string, AlbumRow[]>();
    for (const row of result.rows) {
      pushGrouped(map, groupKey(String(row.chat_id), String(row.grouped_id)), toAlbumRow(row));
    }
    return map;
  }

  private table(name: string): string {
    return `${this.schema}.${quoteIdentifier(name)}`;
  }
}

function messageSelect(messages: string, mediaFiles: string): string {
  return `SELECT
      m.id::text AS row_id,
      m.message_id,
      m.chat_id,
      m.grouped_id,
      m.chat_title,
      m.date,
      m.sender_id,
      m.sender_username,
      m.sender_first_name,
      m.sender_last_name,
      m.has_media,
      m.media_type,
      m.message_type,
      m.text,
      media_meta.mime_type
    FROM ${messages} m
    LEFT JOIN LATERAL (
      SELECT mf.mime_type
        FROM ${mediaFiles} mf
       WHERE mf.message_id = m.message_id AND mf.chat_id = m.chat_id
       ORDER BY mf.id DESC
       LIMIT 1
    ) media_meta ON TRUE`;
}

function albumSelect(messages: string, mediaFiles: string): string {
  return `SELECT
      m.id::text AS row_id,
      m.message_id,
      m.chat_id,
      m.grouped_id,
      m.date,
      m.has_media,
      m.media_type,
      m.message_type,
      media_meta.mime_type
    FROM ${messages} m
    LEFT JOIN LATERAL (
      SELECT mf.mime_type
        FROM ${mediaFiles} mf
       WHERE mf.message_id = m.message_id AND mf.chat_id = m.chat_id
       ORDER BY mf.id DESC
       LIMIT 1
    ) media_meta ON TRUE`;
}

function buildWhere(query: ArchiveQuery): { where: string; values: string[] } {
  const conditions: string[] = [];
  const values: string[] = [];
  const add = (condition: string, value: string): void => {
    values.push(value);
    conditions.push(condition.replace("$N", `$${values.length}`));
  };
  for (const term of splitTerms(query.keyword)) add("m.text ILIKE $N", `%${term}%`);
  for (const term of splitTerms(query.excludeKeyword)) add("m.text NOT ILIKE $N", `%${term}%`);
  if (query.chatId?.trim()) add("m.chat_id = $N", query.chatId.trim());
  if (query.chatTitle?.trim()) add("m.chat_title ILIKE $N", `%${query.chatTitle.trim()}%`);
  appendTimeWhere(conditions, values, query, add);
  return { where: conditions.length ? `WHERE ${conditions.join(" AND ")}` : "", values };
}

function appendTimeWhere(
  conditions: string[],
  values: string[],
  query: ArchiveQuery,
  add: (condition: string, value: string) => void
): void {
  const mode = normalizeTimeMode(query.timeMode);
  if (mode === "off" || (!query.dateFrom && !query.dateTo)) return;
  if (mode === "include") {
    if (query.dateFrom) add("m.date >= $N::timestamptz", query.dateFrom);
    if (query.dateTo) add("m.date <= $N::timestamptz", query.dateTo);
    return;
  }
  if (query.dateFrom && query.dateTo) {
    const fromIndex = values.length + 1;
    values.push(query.dateFrom, query.dateTo);
    conditions.push(
      `NOT (m.date >= $${fromIndex}::timestamptz AND m.date <= $${fromIndex + 1}::timestamptz)`
    );
  } else if (query.dateFrom) {
    add("m.date < $N::timestamptz", query.dateFrom);
  } else if (query.dateTo) {
    add("m.date > $N::timestamptz", query.dateTo);
  }
}

function pairSql(
  column: string,
  pairs: readonly (readonly [string, string | number])[]
): { clause: string; params: (string | number)[] } {
  const params: (string | number)[] = [];
  const parts: string[] = [];
  for (const [chatId, second] of pairs) {
    const start = params.length + 1;
    parts.push(`(chat_id = $${start} AND ${column} = $${start + 1})`);
    params.push(chatId, second);
  }
  return { clause: parts.join(" OR "), params };
}

function toStoredMediaFile(row: QueryResultRow): StoredMediaFile {
  return {
    id: String(row.id),
    messageId: Number(row.message_id),
    chatId: String(row.chat_id),
    mediaType: String(row.media_type ?? "document"),
    fileName: optionalString(row.file_name),
    filePath: optionalString(row.file_path),
    fileSize: optionalNumber(row.file_size),
    mimeType: optionalString(row.mime_type)
  };
}

function toAlbumRow(row: QueryResultRow): AlbumRow {
  return {
    rowId: String(row.row_id),
    messageId: Number(row.message_id),
    chatId: String(row.chat_id),
    groupedId: String(row.grouped_id),
    date: toIsoDate(row.date),
    hasMedia: Boolean(row.has_media),
    mediaType: optionalString(row.media_type),
    messageType: optionalString(row.message_type),
    mimeType: optionalString(row.mime_type)
  };
}

function toMessageRecord(
  row: QueryResultRow,
  mediaMap: Map<string, StoredMediaFile[]>,
  albumMap: Map<string, AlbumRow[]>
): MessageRecord {
  const chatId = String(row.chat_id);
  const messageId = Number(row.message_id);
  const groupedId = optionalString(row.grouped_id);
  const mediaFiles = mediaMap.get(mediaKey(chatId, messageId)) ?? [];
  const albumRows = groupedId !== undefined ? albumMap.get(groupKey(chatId, groupedId)) ?? [] : [];
  return {
    rowId: String(row.row_id),
    messageId,
    chatId,
    groupedId,
    chatTitle: optionalString(row.chat_title),
    date: toIsoDate(row.date),
    senderId: optionalString(row.sender_id),
    senderUsername: optionalString(row.sender_username),
    senderFirstName: optionalString(row.sender_first_name),
    senderLastName: optionalString(row.sender_last_name),
    hasMedia: Boolean(row.has_media),
    mediaType: optionalString(row.media_type),
    messageType: optionalString(row.message_type) ?? "text",
    mimeType: optionalString(row.mime_type),
    text: String(row.text ?? ""),
    mediaFiles,
    albumRows
  };
}

function pushGrouped<T>(map: Map<string, T[]>, key: string, item: T): void {
  let items = map.get(key);
  if (!items) {
    items = [];
    map.set(key, items);
  }
  items.push(item);
}

function quoteIdentifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}

function optionalString(value: unknown): string | undefined {
  return value === undefined || value === null || value === "" ? undefined : String(value);
}

function optionalNumber(value: unknown): number | undefined {
  return value === undefined || value === null || value === "" ? undefined : Number(value);
}